codecov:
  notify:
    require_ci_to_pass: true
comment:
  behavior: default
  layout: header, diff
  require_changes: false
coverage:
  precision: 2
  range:
  - 70.0
  - 100.0
  round: down
  status:
    changes: false
    patch: true
    project:
      default:
        target: 95
        threshold: 1
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
  javascript:
    enable_partials: false
ignore:
  - "src/**/*_test.py"
